image_video: image_video
    lien: lien
    md_bg_color: "#262626"

    MDBoxLayout:
        orientation:"horizontal"
        spacing: dp(10)

        MDBoxLayout:
            orientation:"vertical"
            spacing: dp(10)

            MDBoxLayout:
                orientation:"horizontal"
                spacing: dp(10)
                size_hint_y: 0.1

                MDTextField:
                    id: lien
                    hint_text: "Entre le Lien:"
                    hint_text_color_normal: "white"
                    hint_text_color_focus: "white"
                    text_color_focus: "white"
                    text_color_normal: "white"
                    line_color_normal: "white"
                    line_color_focus: "white"
                    #pos_hint: {"x": 0.1}
                    #size_hint: 0.5, 0.5

                MDRectangleFlatIconButton:
                    id: camera
                    icon: "camera"
                    text: "Camera"
                    icon_color: "white"
                    text_color: "white"
                    line_color: "white"
                    theme_icon_color: "Custom"
                    #pos_hint: {"x": .2}
                    on_release: app.lancer()

            MDBoxLayout:
                orientation:"horizontal"
                spacing: dp(3)
                padding: dp(5)
                size_hint_y: 0.5
               # md_bg_color: "#55ff7f"

                Image:
                    id: image_video
                    size_hint: .5, .5
                    pos_hint: {"center_x": .2, "center_y": .5}

                MDBoxLayout:
                    orientation:"vertical"
                    spacing: dp(10)
                    padding: dp(10)

                    MDBoxLayout:
                        orientation: "horizontal"

                        MDLabel:
                            text: "format : "

                        MDRaisedButton:
                            id: button_format
                            text: "Select format video"
                            pos_hint: {"center_x": .5, "center_y": .5}
                            #on_release: app.menu_open()

                    MDRectangleFlatIconButton:
                        id: camera
                        icon: "crop-landscape"
                        text: "Capture"
                        pos_hint: {"center_x": .3, "top": .7}
                        icon_color: "white"
                        text_color: "white"
                        line_color: "white"
                        theme_icon_color: "Custom"
                        on_release: app.captureCamera()

                    MDRectangleFlatIconButton:
                        id: save
                        icon: "content-save"
                        text: "Enregistrer"
                        pos_hint: {"center_x": .3, "top": .5}
                        icon_color: "white"
                        text_color: "white"
                        line_color: "white"
                        theme_icon_color: "Custom"
                        on_release: app.enregistrer()

                    MDRectangleFlatIconButton:
                        id: stop
                        icon: "stop"
                        text: "Stop"
                        pos_hint: {"center_x": .3, "top": .3}
                        icon_color: "white"
                        text_color: "white"
                        line_color: "white"
                        theme_icon_color: "Custom"
                        on_release: app.stop()


            MDBoxLayout:
                orientation:"horizontal"
                size_hint_y: 0.4

        MDBoxLayout:
            md_bg_color: "#484848"
            padding: dp(10)
            spacing: dp(10)
            orientation: "vertical"

            MDGridLayout:
                spacing: dp(10)
                cols: 2

                CardImage:
                    id: 1
                CardImage:
                    id: 2
                CardImage:
                    id: 3
                CardImage:
                    id: 4

            MDWidget:
                size_hint_y: .5

<CardImagetest>:
    md_bg_color: "#262626"

    MDRelativeLayout:
        md_bg_color: "#262626"

        Image:
            id: image
            size_hint: .98, .98
            pos_hint: {"center_x": .5, "center_y": .5}

        MDBoxLayout:
            orientation: "vertical"
            spacing: "2sp"
            pos_hint: {"center_x": .98}

            MDIconButton:
                icon: "menu"
                size_hint: .1, .1
                icon_color: "green"

            MDIconButton:
                icon: "crop-landscape"
                size_hint: .1, .1
                icon_color: "green"
                adaptive_height: True

            MDIconButton:
                icon: "content-save"
                size_hint: .1, .1
                color: "green"
                adaptive_height: True

            MDIconButton:
                icon: "stop"
                size_hint: .1, .1
                icon_color: "green"
                adaptive_height: True